// Destinatarios institucionales del Calendario OMO.
// Generado a partir de los CSV exportados de Google Groups.
// No contiene contraseñas, tokens ni secretos.

const ASISTENTES_OMO = [
  "alvaro.vergara@eduvaldivia.gob.cl",
  "barbara.barrientos@eduvaldivia.gob.cl",
  "bladimir.vargas@eduvaldivia.gob.cl",
  "bryan.fernandez@eduvaldivia.gob.cl",
  "carlos.catalan2@eduvaldivia.gob.cl",
  "carolina.aguilera1@eduvaldivia.gob.cl",
  "carolina.catalan@eduvaldivia.gob.cl",
  "caroline.godoy@eduvaldivia.gob.cl",
  "cesar.catalan@eduvaldivia.gob.cl",
  "claudio.morales@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "daniela.naipan@eduvaldivia.gob.cl",
  "gabriela.delgado@eduvaldivia.gob.cl",
  "genesis.zevallos@eduvaldivia.gob.cl",
  "gonzalo.espinoza@eduvaldivia.gob.cl",
  "greimar.castro@eduvaldivia.gob.cl",
  "gricelda.cardenas@eduvaldivia.gob.cl",
  "javiera.quichiyao@eduvaldivia.gob.cl",
  "jessica.riffo@eduvaldivia.gob.cl",
  "joaquin.andrade@eduvaldivia.gob.cl",
  "juana.vega@eduvaldivia.gob.cl",
  "loreto.zenteno@eduvaldivia.gob.cl",
  "marcia.reyes@eduvaldivia.gob.cl",
  "margareth.albrecht@eduvaldivia.gob.cl",
  "maria.alvarez@eduvaldivia.gob.cl",
  "maria.munozv@eduvaldivia.gob.cl",
  "michael.meneses@eduvaldivia.gob.cl",
  "monica.arriagada@eduvaldivia.gob.cl",
  "monica.arriagadaf@eduvaldivia.gob.cl",
  "roberto.delgadillo@eduvaldivia.gob.cl",
  "rosalia.salas@eduvaldivia.gob.cl",
  "sandra.banados@eduvaldivia.gob.cl",
  "sebastian.aguilar@eduvaldivia.gob.cl",
  "victor.casanova@eduvaldivia.gob.cl",
  "yarela.pinuer@eduvaldivia.gob.cl",
  "yocelyn.vejar@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
  "yorka.naegel@eduvaldivia.gob.cl",
];

const ASISTENTES_PROFESIONALES_OMO = [
  "alvaro.vergara@eduvaldivia.gob.cl",
  "barbara.barrientos@eduvaldivia.gob.cl",
  "bladimir.vargas@eduvaldivia.gob.cl",
  "bryan.fernandez@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "genesis.zevallos@eduvaldivia.gob.cl",
  "javiera.quichiyao@eduvaldivia.gob.cl",
  "joaquin.andrade@eduvaldivia.gob.cl",
  "juana.vega@eduvaldivia.gob.cl",
  "margareth.albrecht@eduvaldivia.gob.cl",
  "sandra.banados@eduvaldivia.gob.cl",
  "sebastian.aguilar@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const CONVIVENCIA_OMO = [
  "alvaro.vergara@eduvaldivia.gob.cl",
  "bryan.fernandez@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "maria.salgado@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const DOCENTES_OMO = [
  "adriana.gallardo@eduvaldivia.gob.cl",
  "ana.molina@eduvaldivia.gob.cl",
  "ana.valderrama@eduvaldivia.gob.cl",
  "analya.olivares@eduvaldivia.gob.cl",
  "antonio.leiva@eduvaldivia.gob.cl",
  "aracelly.fuentealba@eduvaldivia.gob.cl",
  "beatriz.reyes@eduvaldivia.gob.cl",
  "braulio.alvarez@eduvaldivia.gob.cl",
  "carolina.delgado1@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "daniela.reyes1@eduvaldivia.gob.cl",
  "deisy.fuchslocher@eduvaldivia.gob.cl",
  "diego.ortega@eduvaldivia.gob.cl",
  "espartaco.uribe@eduvaldivia.gob.cl",
  "evelyn.zenteno@eduvaldivia.gob.cl",
  "fredy.carrillo@eduvaldivia.gob.cl",
  "gabriel.guzman@eduvaldivia.gob.cl",
  "guisella.schwartinsky@eduvaldivia.gob.cl",
  "jeannette.montecinos@eduvaldivia.gob.cl",
  "johana.risco@eduvaldivia.gob.cl",
  "juana.villanueva@eduvaldivia.gob.cl",
  "karen.flandez@eduvaldivia.gob.cl",
  "karina.ulloa@eduvaldivia.gob.cl",
  "katherine.solis@eduvaldivia.gob.cl",
  "luis.castro@eduvaldivia.gob.cl",
  "madelyn.rodriguez@eduvaldivia.gob.cl",
  "maite.moena@eduvaldivia.gob.cl",
  "marcela.fernandez@eduvaldivia.gob.cl",
  "margareth.solis@eduvaldivia.gob.cl",
  "maria.escalona@eduvaldivia.gob.cl",
  "maria.quezada1@eduvaldivia.gob.cl",
  "maria.salgado@eduvaldivia.gob.cl",
  "mariana.huala@eduvaldivia.gob.cl",
  "mark.morales@eduvaldivia.gob.cl",
  "marlis.reyes@eduvaldivia.gob.cl",
  "matias.mansilla@eduvaldivia.gob.cl",
  "melania.jaramillo@eduvaldivia.gob.cl",
  "monica.vasquez@eduvaldivia.gob.cl",
  "nuris.pinilla@eduvaldivia.gob.cl",
  "patricia.inoque@eduvaldivia.gob.cl",
  "patricia.torres1@eduvaldivia.gob.cl",
  "priscila.rivas@eduvaldivia.gob.cl",
  "rebeca.orellana@eduvaldivia.gob.cl",
  "rocio.huichaqueo@eduvaldivia.gob.cl",
  "rosa.plaza@eduvaldivia.gob.cl",
  "susana.santana@eduvaldivia.gob.cl",
  "tamara.plaza@eduvaldivia.gob.cl",
  "victor.carrasco@eduvaldivia.gob.cl",
  "ximena.jara@eduvaldivia.gob.cl",
  "yessica.oporto@eduvaldivia.gob.cl",
  "yohanna.lara@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const EDUCADORAS_DIFERENCIALES_OMO = [
  "adriana.gallardo@eduvaldivia.gob.cl",
  "carolina.delgado1@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "deisy.fuchslocher@eduvaldivia.gob.cl",
  "evelyn.zenteno@eduvaldivia.gob.cl",
  "johana.risco@eduvaldivia.gob.cl",
  "mariana.huala@eduvaldivia.gob.cl",
  "nuris.pinilla@eduvaldivia.gob.cl",
  "tamara.plaza@eduvaldivia.gob.cl",
  "ximena.jara@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const EQUIPO_DIRECTIVO_OMO = [
  "antonio.leiva@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "fredy.carrillo@eduvaldivia.gob.cl",
  "luis.castro@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const INSPECTORIA_OMO = [
  "antonio.leiva@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "gabriela.delgado@eduvaldivia.gob.cl",
  "jessica.riffo@eduvaldivia.gob.cl",
  "luis.castro@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
  "yorka.naegel@eduvaldivia.gob.cl",
];

const MEDIAOMO = [
  "ana.molina@eduvaldivia.gob.cl",
  "aracelly.fuentealba@eduvaldivia.gob.cl",
  "carolina.delgado1@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "diego.ortega@eduvaldivia.gob.cl",
  "karen.flandez@eduvaldivia.gob.cl",
  "katherine.solis@eduvaldivia.gob.cl",
  "margareth.solis@eduvaldivia.gob.cl",
  "mariana.huala@eduvaldivia.gob.cl",
  "mark.morales@eduvaldivia.gob.cl",
  "matias.mansilla@eduvaldivia.gob.cl",
  "nuris.pinilla@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const NT_OMO = [
  "beatriz.reyes@eduvaldivia.gob.cl",
  "caroline.godoy@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "gricelda.cardenas@eduvaldivia.gob.cl",
  "karina.ulloa@eduvaldivia.gob.cl",
  "loreto.zenteno@eduvaldivia.gob.cl",
  "patricia.inoque@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
  "yuslein.sepulveda@eduvaldivia.gob.cl",
];

const OCB_OMO = [
  "cesar.catalan@eduvaldivia.gob.cl",
  "claudio.morales@eduvaldivia.gob.cl",
  "franklin.delima@eduvaldivia.gob.cl",
  "gabriel.guzman@eduvaldivia.gob.cl",
  "gonzalo.espinoza@eduvaldivia.gob.cl",
  "michael.meneses@eduvaldivia.gob.cl",
  "roberto.delgadillo@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const PRIMER_CICLO_OMO = [
  "analya.olivares@eduvaldivia.gob.cl",
  "carolina.aguilera1@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "guisella.schwartinsky@eduvaldivia.gob.cl",
  "jeannette.montecinos@eduvaldivia.gob.cl",
  "madelyn.rodriguez@eduvaldivia.gob.cl",
  "maria.quezada1@eduvaldivia.gob.cl",
  "marlis.reyes@eduvaldivia.gob.cl",
  "melania.jaramillo@eduvaldivia.gob.cl",
  "rosa.plaza@eduvaldivia.gob.cl",
  "susana.santana@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const SEGUNDO_CICLO_OMO = [
  "ana.molina@eduvaldivia.gob.cl",
  "ana.valderrama@eduvaldivia.gob.cl",
  "aracelly.fuentealba@eduvaldivia.gob.cl",
  "braulio.alvarez@eduvaldivia.gob.cl",
  "daniel.baez@eduvaldivia.gob.cl",
  "daniela.reyes1@eduvaldivia.gob.cl",
  "espartaco.uribe@eduvaldivia.gob.cl",
  "juana.villanueva@eduvaldivia.gob.cl",
  "karen.flandez@eduvaldivia.gob.cl",
  "katherine.solis@eduvaldivia.gob.cl",
  "maite.moena@eduvaldivia.gob.cl",
  "marcela.fernandez@eduvaldivia.gob.cl",
  "margareth.solis@eduvaldivia.gob.cl",
  "maria.escalona@eduvaldivia.gob.cl",
  "mariana.huala@eduvaldivia.gob.cl",
  "matias.mansilla@eduvaldivia.gob.cl",
  "melania.jaramillo@eduvaldivia.gob.cl",
  "nuris.pinilla@eduvaldivia.gob.cl",
  "tamara.plaza@eduvaldivia.gob.cl",
  "yessica.oporto@eduvaldivia.gob.cl",
  "yonatan.huentemilla@eduvaldivia.gob.cl",
];

const CORREOS_POR_ETIQUETA = {
  "asistentes.omo@eduvaldivia.gob.cl": ASISTENTES_OMO,
  "asistentes.profesionales.omo@eduvaldivia.gob.cl": ASISTENTES_PROFESIONALES_OMO,
  "convivencia.omo@eduvaldivia.gob.cl": CONVIVENCIA_OMO,
  "docentes.omo@eduvaldivia.gob.cl": DOCENTES_OMO,
  "educadoras.diferenciales.omo@eduvaldivia.gob.cl": EDUCADORAS_DIFERENCIALES_OMO,
  "equipo.directivo.omo@eduvaldivia.gob.cl": EQUIPO_DIRECTIVO_OMO,
  "inspectoria.omo@eduvaldivia.gob.cl": INSPECTORIA_OMO,
  "mediaomo@eduvaldivia.gob.cl": MEDIAOMO,
  "nt.omo@eduvaldivia.gob.cl": NT_OMO,
  "ocb.omo@eduvaldivia.gob.cl": OCB_OMO,
  "primer.ciclo.omo@eduvaldivia.gob.cl": PRIMER_CICLO_OMO,
  "segundo.ciclo.omo@eduvaldivia.gob.cl": SEGUNDO_CICLO_OMO,
};

module.exports = {
  ASISTENTES_OMO,
  ASISTENTES_PROFESIONALES_OMO,
  CONVIVENCIA_OMO,
  DOCENTES_OMO,
  EDUCADORAS_DIFERENCIALES_OMO,
  EQUIPO_DIRECTIVO_OMO,
  INSPECTORIA_OMO,
  MEDIAOMO,
  NT_OMO,
  OCB_OMO,
  PRIMER_CICLO_OMO,
  SEGUNDO_CICLO_OMO,
  CORREOS_POR_ETIQUETA,
};
