CREATE TABLE IF NOT EXISTS users(
 id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'Publicador',can_publish BOOLEAN NOT NULL DEFAULT FALSE,
 active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS event_categories(
 id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,color TEXT NOT NULL DEFAULT '#1E88E5',
 active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS events(
 id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,event_date DATE NOT NULL,start_time TIME NOT NULL,
 end_time TIME NOT NULL,place TEXT NOT NULL DEFAULT '',area TEXT NOT NULL,
 description TEXT NOT NULL DEFAULT '',created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
 created_by_name TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),category_id BIGINT REFERENCES event_categories(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
